# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docling-serve
  namespace: docling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docling-serve
  template:
    metadata:
      labels:
        app: docling-serve
    spec:
      containers:
      - name: docling-serve
        image: ghcr.io/docling-project/docling-serve-cpu
        ports:
        - containerPort: 5001
